### ISSUE TITLE
Unable to resize windows

### ISSUE THREAD

**Issue by jcr723** [skyguy126/GCI#4]
Guys...not sure if "issues" on GitHub should include enhancements rather than outright bugs but I'll log enhancements/modification requests here for now.  Since we didn't have a detailed requirements document, there will likely be quite a few of these initially.

Current issues:
Attempted to widen log window to capture comments for feedback to student.  But window won't widen.  Also, there should be an button that resizes all 3 windows to default, full screen, non-overlapping view

**Comment by skyguy126** [comment]
@jcr723 The windows are not resizable, this is by design of the program, mostly to make it look uncluttered. This _should_ (design change) be implemented in the future but for now you can click on the `Task` menu in the log window, then save the log (creates a **.txt** file which can be viewed with notepad or some other plain text reader). Will work on a better solution for the next version.

**Comment by skyguy126** [comment]
Added feature with commit 912ca3f400fe755e5afb902dc516336c12a90587.
